### ISSUE TITLE
Geeting Invalid API token

### ISSUE THREAD

**Issue by ashishmmt** [raghavan/InstantQnA#1]
I Was trying to run this code but getting below error:

➜  InstantQnA git:(main) ✗ python3 main.py

                                        Instant Q&A Builder                                         

ai_generated/embeds/bill (2).pdf.json EMBED NOT FOUND

Reading pdf text content: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 308.78it/s]

Creating dataset: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 89.60it/s]

Calculating total token: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 294.01it/s]

0 tokens in total, (approx. $0.0)
Would you like to embed? (y/n)y
Embedding files:   0%|                                                                                                                                                                                              | 0/1 [00:00<?, ?it/s]huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)
huggingface/tokenizers: The current process just got forked, after parallelism has already been used. Disabling parallelism to avoid deadlocks...
To disable this warning, you can either:
	- Avoid using `tokenizers` before the fork if possible
	- Explicitly set the environment variable TOKENIZERS_PARALLELISM=(true | false)

**Invalid API token**
Embedding files: 100%|█

**Comment by alfvar** [comment]
I had this issue, turned out I needed to upgrade to a pay-as-you-go account on openAPI. It can only parse a certain amount of tokens per request.

**Comment by raghavan** [comment]
Yes, you need a pay-as-you-go account on openAPI.
